
/*
Comprobar el funcionamiento del programa y el código descrito en el ejemplo 2. Eliminar el botón añadido y hacer que cada uno de
los botones de colores permita, al pulsarlo, detener y reanudar al pintor correspondiente, de forma que podamos parar el cambio de
color de cada botón de manera independiente.
*/
package Ejercicio2;


public class Colores extends javax.swing.JFrame
{
     private Paso paso1 = new Paso();
    private Paso paso2 = new Paso(); 
    private Paso paso3 = new Paso();
    private Paso paso4 = new Paso();
    private boolean botonPulsado = false;

    /** Creates new form Colores */
    public Colores()
    {
        initComponents();
        Paleta parchis = new Paleta();
        Pintor p1 = new Pintor(jButton1,parchis,paso1);
        Pintor p2 = new Pintor(jButton2,parchis,paso2);
        Pintor p3 = new Pintor(jButton3,parchis,paso3);
        Pintor p4 = new Pintor(jButton4,parchis,paso4);
        p1.start();
        p2.start();
        p3.start();
        p4.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colores");

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Detener");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Detener");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Detener");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Detener");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(816, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!botonPulsado) //Si no se ha pulsado
        {                 
            botonPulsado=true;             //lo cambiamos a pulsado
            jButton1.setText("Reanudar");  //y cambiamos el texto
            paso1.cerrar();    //Cerramos el paso para que los pintores se detengan
        }
        else //Si ya se había pulsado
        {                           
            botonPulsado=false;            //lo cambiamos
            jButton1.setText("Detener");  //y cambiamos el texto
            paso1.abrir();    //Abrimos el paso para que los pintores sigan trabajando
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(!botonPulsado) //Si no se ha pulsado
        {                 
            botonPulsado=true;             //lo cambiamos a pulsado
            jButton2.setText("Reanudar");  //y cambiamos el texto
            paso2.cerrar();    //Cerramos el paso para que los pintores se detengan
        }
        else //Si ya se había pulsado
        {                           
            botonPulsado=false;            //lo cambiamos
            jButton2.setText("Detener");  //y cambiamos el texto
            paso2.abrir();    //Abrimos el paso para que los pintores sigan trabajando
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!botonPulsado) //Si no se ha pulsado
        {                 
            botonPulsado=true;             //lo cambiamos a pulsado
            jButton3.setText("Reanudar");  //y cambiamos el texto
            paso3.cerrar();    //Cerramos el paso para que los pintores se detengan
        }
        else //Si ya se había pulsado
        {                           
            botonPulsado=false;            //lo cambiamos
            jButton3.setText("Detener");  //y cambiamos el texto
            paso3.abrir();    //Abrimos el paso para que los pintores sigan trabajando
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(!botonPulsado) //Si no se ha pulsado
        {                 
            botonPulsado=true;             //lo cambiamos a pulsado
            jButton4.setText("Reanudar");  //y cambiamos el texto
            paso4.cerrar();    //Cerramos el paso para que los pintores se detengan
        }
        else //Si ya se había pulsado
        {                           
            botonPulsado=false;            //lo cambiamos
            jButton4.setText("Detener");  //y cambiamos el texto
            paso4.abrir();    //Abrimos el paso para que los pintores sigan trabajando
        }
    }//GEN-LAST:event_jButton4ActionPerformed

   
    
    
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new Colores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
